window.addEventListener("load", function() {

    const firstName = [
        "Silky",
        "Hell",
        "Saucy",
        "Juicy",
        "Vitamin",
        "Minty",
        "Phoenix",
        "Alaska",
        "Roxy",
        "Foxy",
        "Ginger",
        "Pearl",
        "Disco",
        "Calamity",
        "Genevieve",
        "Elle",
        "Love",
        "Brooklyn",
        "Charlize",
        "Rhinestone",
        "Diamond",
        "Pinot",
        "Sugar",
        "Salty",
        "Dorthy",
        "Vanessa",
        "Angela",
        "Tamara",
        "Diana",
        "Tia",
        "Doja",
        "Harlette",
        "Ashley",
        "Trixie",
        "Katya",
        "Ben",
        "Becky",
        "Carol",
        "Belle",
        "Delphine",
        "Anastasia",
        "Violet",
        "Tyra",
        "Raven",
        "Basil",
        "Sofia",
        "Mariah",
        "Almond",
        "Pecan",
        "Princess",
        "Ivy",
        "Jasmine",
        "DuJour",
        "Fame",
        "Noami",
        "Bambi",
        "Gigi",
        "Berry",
        "Jane",
        "Mary",
        "Dingo",
        "Cherry",
        "Strawberry",
        "Foster",
        "Golden",
        "Azalea",
        "Lily",
        "Yasmin",
        "Zinnia",
        "Poppy",
        "Daisy",
        "Dahlia",
        "Sage",
        "Cedar",
        "Ren",
        "Crying",
        "Indigo",
        "Sorrel",
        "Glossy",
        "Dongo",
        "Virginia",
        "Uh oh",
        "Bikini Martini",
        "Smile Like",
        "One Way to",
        "Lonesome",
        "Mac",
        "Lenny",
        "Reverend",
        "Flaco",
        "Rattlesnake",
        "Ol’",
        "Copperhead",
        "Desperado",
        "Tumbleweed",
        "Cannonball",
        "Scarlett",
        "Laramie",
        "Cimarron",
        "Amarillo",
        "Cochise",
        "Tornado",
        "Silver",
        "Tucson",
        "Sedona",
        "Cry Like",
        "Built Like",
        "Notorious",
        "Otherwise Known as",
        "Also Known As",
        "Formerly",
        "Once Called",
        "Chicken Dog",
        "Hope Child",
        "Sivka"
    ];

    const lastName = [
        "Pandemonium",
        "the Noodle",
        "the Essence",
        "the Jay",
        "the Sauce",
        "the Sweet",
        "Cherry",
        "Cinnamon",
        "the Cherry",
        "Ketchup",
        "Moon",
        "Jalfo",
        "Dolphin",
        "the Moon",
        "Leopard",
        "the Fox",
        "the Chicken",
        "Lion",
        "George",
        "Bells",
        "Duvet",
        "the Gossip",
        "Kay",
        "Mustard",
        "the Phoenix",
        "Ritz",
        "the Ritz",
        "Princess",
        "Buchanan",
        "Mayonnaise",
        "Chanel",
        "Pearl",
        "Deficiency",
        "Veloure",
        "Bloodlust",
        "Lux",
        "Evangalista",
        "Frank",
        "Joe",
        "Willow",
        "Hamburger",
        "Balloon",
        "Pancake",
        "the Corndog",
        "Hotdog",
        "Sorbet",
        "Dango",
        "the Juice",
        "the Strawberry",
        "Cartoon",
        "Money",
        "the Bunny",
        "Shampoo",
        "Foster",
        "the Joe",
        "the Posh",
        "the Primrose",
        "Poppins",
        "Au Fait",
        "Julep",
        "High Ball",
        "Christmas",
        "Frontana",
        "Drossel",
        "Supertrix",
        "Goldicat",
        "Nation",
        "Pandowdy",
        "at Midnight",
        "Your Valentine",
        "Jackson",
        "Calloway",
        "Van Der Linde",
        "Stillwater",
        "Annesburg",
        "Rhodes",
        "the Kid",
        "Redemption",
        "Marston",
        "Midnight",
        "Clemens",
        "Citation",
        "Whirlaway",
        "Affirmed",
        "McQueen",
        "Maverick",
        "Cassidy",
        "Dalton",
        "at Dawn",
        "at Sundown",
        "in Disguise",
        "on the Loose",
        "Owes Me Money",
        "Took My Horse",
        "Left Town Fast",
        "Never Came Back",
        "Was Never Here",
        "Didn’t Do It",
        "the Sequel",
        "Part Two",
        "Returns",
        "Stole My Hat",
        "Strikes Back",
        "Rides Again",
        "the Unbroken",
        "Kilgore"
    ];

    let firstNamePool = [];
    let lastNamePool = [];

    function shuffle(arr) {
        for (let i = arr.length - 1; i > 0; i--) {
            const j = Math.floor(Math.random() * (i + 1));
            [arr[i], arr[j]] = [arr[j], arr[i]];
        }
        return arr;
    }

    function refillPool(pool, length) {
        pool.length = 0;
        for (let i = 0; i < length; i++) {
            pool.push(i);
        }
        shuffle(pool);
    }

    function getNextIndex(pool, length) {
        if (pool.length === 0) {
            refillPool(pool, length);
        }
        return pool.pop();
    }

    const form = document.querySelector("form");
    form.addEventListener("submit", function(event) {
        event.preventDefault();

        const firstNameIndex = getNextIndex(firstNamePool, firstName.length);
        const lastNameIndex = getNextIndex(lastNamePool, lastName.length);

        const firstHorseName = firstName[firstNameIndex];
        const lastHorseName = lastName[lastNameIndex];
        const horseName = `${firstHorseName} ${lastHorseName}`;

        document.getElementById('name-display-space').innerHTML = horseName;
    });

});
